### ISSUE TITLE
Add unit tests to cover all possible errors raised.

### ISSUE THREAD

**Issue by seiflotfy** [seiflotfy/skizze#31]
We need to make sure that any method that raises an error has a test for it where it actually raises an error.

**Comment by martinpinto** [comment]
Top level classes:

package counters
manager.go:CreateDomain()
manager.go:DeleteDomain()
manager.go:GetDomains()
manager.go:AddToDomain()
manager.go:DeleteFromDomain()
manager.go:GetCountForDomain()

package server
server.go:handleTopRequest() // http.error
server.go:handleTopDomainRequest() // http.error
server.go:ServeHTTP() // http.error

package storage
manager.go:newManager()
manager.go:Create()
manager.go:SaveData()
manager.go:LoadData()
manager.go:getFileFromCache()
manager.go:loadAllInfo()
manager.go:SaveInfo()

**Comment by martinpinto** [comment]
also under package counters/wrappers all methods that raise an error

**Comment by seiflotfy** [comment]
great job can you start writing tests for those?

**Comment by martinpinto** [comment]
Yeah sure
Am 14.08.2015 1:47 vorm. schrieb "Seif Lotfy" <notifications@github.com>:
