### ISSUE TITLE
Expand GET API

### ISSUE THREAD

**Issue by seiflotfy** [seiflotfy/skizze#35]
* Expand `GET /` API so counters can be filtered using query params
* Add pagination to `GET /` API

**Comment by martinpinto** [comment]
We should allow for the use of wilcards. Let's say you have a domain that tracks all the likes from a given user in EBNF:
```
domain = month , "-" , year , "-" , user , "-" , type ;
month = number , number ;
year = number , number , number , number ;
user = {letter} ;
type = {letter} ;
number = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;
letter = "A" | "B" | "C" | "D" | "E" | "F" | "G"
       | "H" | "I" | "J" | "K" | "L" | "M" | "N"
       | "O" | "P" | "Q" | "R" | "S" | "T" | "U"
       | "V" | "W" | "X" | "Y" | "Z" ;
```
so e.g. "10-2014-MIKE-LIKES" would return the count of all likes from the user MIKE in the month of October 2014. We should allow for "*-2014-MIKE-LIKES" to return the count for all likes from user MIKE in the year 2014.

**Comment by seiflotfy** [comment]
Actually I think this bug is invalid. since redis and other k-v stores that are similar to ours do not allow filtering via queries. You need to know specifically what you are asking for. GET requests are cheap and direct

**Comment by seiflotfy** [comment]
### Filtering using collections and id prefixes

A full blown query/wildcard search over the domain ids isn't easy to implement efficiently using boltdb or leveldb. What we can do is a prefix search over the domain ids and in addition to domain ids group things that will not be queried together in separate collections. For example merging multiple HLL++ domains will always use the same domain type and so it might make sense to have separate collections for each domain type.

**Comment by seiflotfy** [comment]
Also the EBNF is too specific. Its free form so we need to write down a recommended naming scheme for domains

**Comment by martinpinto** [comment]
The EBNF was just to illustrate an example. But I agree with you that we should specify a guideline for recommended naming schemes.

**Comment by seiflotfy** [comment]
I think this all will be referenced with #66
