### ISSUE TITLE
Potential API change

### ISSUE THREAD

**Issue by martinpinto** [seiflotfy/skizze#66]
A domain basically consists of several sketches (e.g. Top-K, HyperLogLog or Count-Min-Log).

Since we are implementing sketches, they would have to be more accesible via API.

I propose a new CRUD layer in the form of:
```
<http-domain>/<sketchId>/_<sketch>
```
which allows you to have the option to specify which sketches you want.

e.g.
localhost:3596/avengers/_cardinality, returns the cardinality for the avengers domain
and
localhost:3596/avengers/_topk/, returns the TopK for the avengers domain.

**Comment by seiflotfy** [comment]
Can you describe how to create a new sketch, update a sketch delete a sketch ?

**Comment by martinpinto** [comment]
**Create:**
```
curl -POST <http-domain>/<sketchId> -d
'{"capacity": uint64}'
```
will create a sketch in all three structures (Top-K, HyperLogLog or Count-Min-Log)

**Update:**
```
curl -PUT <http-domain>/<sketchId> -d
'{"values": [string, string]}'
```
updates a sketch for all three structures

**Delete:**
```
curl -DELETE <http-domain>/<sketchId>/_<sketch>
```
removes a sketch for a particular structure (e.g. we only care about cardinality)
```
curl -DELETE <http-domain>/<sketchId>
```
completely removes a sketch

**Comment by seiflotfy** [comment]
I implemented a new API that requires the sketch type to be given with all requests.
 <http-domain>/<sketchType>/<sketchId>

This gets rid of the concept of domains completely and now everything is a sketch. Also sketches of different types can share the same ID :D
