### ISSUE TITLE
Use "RealCount" up to a threshold before replaying into a probabilistic data structure

### ISSUE THREAD

**Issue by seiflotfy** [seiflotfy/skizze#81]
When creating a new counter (nc) one should be allowed to define a precision threshold that guarantees counts up to a specific  point are 100% accurate by using a dictionary. Once that threshold is reached the dictionary is replayed into the new counter (nc) for probability counting.

**Comment by martinpinto** [comment]
If one should be able to define a precision threshold, then this should be part of the configuration. We should also provide a default threshold in case no threshold is provided.

**Comment by seiflotfy** [comment]
not now at least
